version: 0.2
#env:
#    variables:
#       AWS_DEFAULT_REGION: "eu-west-3"
#       AWS_ACCOUNT_ID: "080266302756"
#    parameter-store:
#       AWS_ECR_REPO: "/devops/AWS_ECR_REPO"

phases:
  install:
      runtime-versions:
          nodejs: 16
  pre_build:
    commands:
      - echo pre_build.....
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
        - aws s3 cp --recursive --acl public-read ./build s3://react-app-cloudfront-08-07-2022

        #- >
        #  aws s3 cp --acl public-read
        #  --cache-control="max-age, no-cache, no-store, must-revalidate"
        #  ./build/service-worker.js s3://react-app-cloudfront-08-07-2022

        - aws cloudfront create-invalidation --distribution-id E2HQF5JDM1L4S3	 --paths /*
artifacts:
    files: 
      - build/**
      - scripts/*
      - nginx.conf
      - appspec.yml